= Devnexus 22: 'Java on Kubernetes: What I wish I knew first' tools demo
:asciidoctor-docs-url: https://docs.asciidoctor.org/
:toc: preamble
:validation: You should be able to access the https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready[Actuator] endpoint http://localhost:8080/actuator.
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
:twitter-uri: https://twitter.com
:github-uri: https://github.com

Demo for the second section of https://devnexus.com/presentations/6947/[Java on Kubernetes: What I wish I knew first] presented at Devnexus 2022.
It shows how to obtain a good dev experience for Java on Kubernetes.
For the whole presentation, see `presentation` dir.

Authors:

* Alberto C. Ríos: {twitter-uri}/albertoimpl[@albertoimpl] on Twitter, {github-uri}/Albertoimpl/[Albertoimpl] on GitHub
* Abel Salgado Romero: {twitter-uri}/albertoimpl[@abelsromero] on Twitter, {github-uri}/Albertoimpl/[abelsromero] on GitHub

== Requirements

* https://www.docker.com/[Docker]
* https://kind.sigs.k8s.io/[Kind]: to create a simplified local K8s cluster.
* https://skaffold.dev/[Skaffold]: to automate, build, deploy and debugging, with life-reload.
Debugging requires IntelliJ https://plugins.jetbrains.com/plugin/8079-cloud-code[Cloud Code plugin].

== Build & Deploy

WARNING: deploying in just Docker or local K8s requires the minimal setup, but also require more manual steps.
And doesn't allow for life-reload and code debugging from IntelliJ.

=== Docker only

To run in plain Docker, build the image and run it.

 $ ./gradlew bootBuildImage
 $ docker run -it -p8080:8080 devnexus:0.0.1-SNAPSHOT

=== Kubernetes (from scratch)

. Start a local Kind cluster

 $ kind create cluster --config kind-config.yaml

. Build Spring Boot docker image

 $ ./gradlew bootBuildImage

. Load image into Kind

 $ kind load docker-image devnexus:0.0.1-SNAPSHOT

. Deploy in Kind's K8s cluster

 $ kubectl apply -f manifests/

To validate it:

 $ kubectl port-forward service/devnexus-svc 8080:8080

{validation}

[NOTE]
====
Project contains a modified version of https://github.com/kubernetes-sigs/metrics-server/releases/download/metrics-server-helm-chart-3.8.2/components.yaml adding `--kubelet-insecure-tls`.
Without this change metrics-server pod won't start with error
----
scraper.go:140] "Failed to scrape node" err="Get \"https://172.18.0.2:10250/metrics/resource\": x509: cannot validate certificate for 172.18.0.2 because it doesn't contain any IP SANs" node="kind-21-worker"
----
====

=== Skaffold

Skaffold automates the complete process of building, deploying, port-forwarding and debugging.
It also offers life-reload, so that changes in the code ar automatically deployed in the local k8s cluster.

To just run without debugging

 $ skaffold dev

{validation}

For debugging install https://plugins.jetbrains.com/plugin/8079-cloud-code[Cloud Code plugin] in IntelliJ.
Create a `Cloud Code: Kubernetes` with the `Run > Edit Configurations` option, and run it as `Debug`.

You should see the app logs in the ID console and be able to add breakpoints and debug as any other Java app.

=== Running in minikube

  $ minikube start --kubernetes-version=v1.21.10

== Features

=== Metrics
// https://github.com/kubernetes-sigs/metrics-server/releases/download/metrics-server-helm-chart-3.8.2/components.yaml
// kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

Skaffold deployment adds https://github.com/kubernetes-sigs/metrics-server[metrics server] adapted for Kind.
Once <<_skaffold,deployed>>, you can check the resources used by the pod with

 $ kubectl top pods