---
apiVersion: v1
kind: Namespace
metadata:
  name: devnexus
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devnexus
  name: devnexus
  namespace: devnexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devnexus
  template:
    metadata:
      labels:
        app: devnexus
    spec:
      containers:
        - image: devnexus:0.0.1-SNAPSHOT
          name: devnexus
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: devnexus
  name: devnexus-svc
  namespace: devnexus
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: devnexus